### ISSUE TITLE
Header covering part of the page .

### ISSUE THREAD

**Issue by jesii-git57** [Tshriju-hub/HostelManagementSystem#6]
The header on the Hostel Management System covers a few parts of the main content area on pages, making it difficult to access certain features and content.

**Comment by Tshriju-hub** [comment]
update: It was caused due to fixed-top class used in main <nav> of header which was used to keep the navbar fixed on the top however since margin-bottom wasn't implemented for in all pages it covered part of the pages it was better to remove it
