### ISSUE TITLE
Unable to Edit Food Packages on Update and Remove Student Page

### ISSUE THREAD

**Issue by jesii-git57** [Tshriju-hub/HostelManagementSystem#9]
When attempting to update or remove a student from the system using the "Update and Remove Student" page, there is no option provided to edit the food packages associated with that student.

**Comment by upasanapaudel9** [comment]
update: The issue preventing the editing of food packages on the "Update and Remove Student" page has been resolved. The user input for the food package was previously disabled, which prevented any edits. This has been corrected by enabling the input field, allowing users to update the food packages as needed.
